### ISSUE TITLE
inclusion in f-droid

### ISSUE THREAD

**Issue by swedebugia** [ddasilva/scheme-droid#4]
Hi.
I created a RFP  https://gitlab.com/fdroid/rfp/issues/851
Do you support the inclusion?

**Comment by ddasilva** [comment]
Sounds good to me.

**Comment by IzzySoft** [comment]
@ddasilva F-Droid maintainer here. To know which commit to build, and have a chance to update in-time, it would tremendoulsy help if you could [tag your releases](https://github.com/ddasilva/scheme-droid/releases). Could you please do so (create a tag whenever you publish a new release)? No need to tag "old ones", starting with the current release is fine. Thanks!

**Comment by ddasilva** [comment]
This project hasn't been updated in four years and there is no further development planned.

**Comment by IzzySoft** [comment]
Ugh. Thanks for the feedback. So the latest commit represents the last version?

**Comment by ddasilva** [comment]
Yup! I can add a tag if it helps you

**Comment by IzzySoft** [comment]
Just checking whether it makes sense to add this to F-Droid if it's no longer maintained (and had no update for 4 years) – but yes, a tag would be nice in any case.

Further, it might be a good idea to "archive" this project then. In case you decide to pick it up again at a later point, you can always "unarchive" it. Until then, the "archive" state would make it clear development is (currently) frozen. What do you think?

**Comment by ddasilva** [comment]
I'll push a tag and then set it to be archived, I didn't know that was a feature.  What would you like the tag to be called?

**Comment by IzzySoft** [comment]
Same as the current versionName, optionally prefixed with a "v" – checking with the current Manifest version, that would be `v1.4`. Thanks!

**Comment by ddasilva** [comment]
A tag was created. Can you confirm it is as you desire? I will then archive the project and you will be unable to comment here. You can reach me at mail@danieldasilva.org if need be.

**Comment by IzzySoft** [comment]
Perfect, thanks! All the best for your other projects then!

**Comment by ddasilva** [comment]
Thanks, and good luck with F-Droid!
